### ISSUE TITLE
introduce  a schema/interface/specification for payload images

### ISSUE THREAD

**Issue by jensfr** [confidential-containers/operator#26]
# introduce a schema/interface/specification for payload images

One goal of the operator is to be runtime agnostic. We want to be able to easily onboard runtimes other than kata-containers.

Currently the controller code is still very specific to kata-deploy. @bpradipt, @fidencio and I brainstormed a bit how we can make it generic. This issue serves to kick off the discussion . We are looking for input from runtime developers and everyone interested. 

Given that
 - runtimes already have a way to deploy on clusters,
 - we don't want to duplicate installers,

the idea is to offer an interface for runtime installers that is so simple that it can be easily mapped to existing operations.

Via the Custom Resource the following can be specified:
 - installation type
 - payload image
 - operation
 - volume
 - hostRequirements

## operations
We keep it simple and start with
- pre-install
- install
- uninstall
- post-uninstall

## payload image
We already have payloadImage defined in our CRD. It should contain binaries, config files etc that are required or the deployment of the runtime. The entrypoint accepts an argument that maps to the operations <pre-install|install|uninstall|post-uninstall|...>

## volumes
Installers require access to paths on the host filesystem. Here a set of volumes are configured that are required when running the operations

## hostRequirements
We'll use the node-feature discovery operator where possible to check cluster nodes for capabilities that runtimes require the host to have in order to function properly. 
For NFD see: https://kubernetes-sigs.github.io/node-feature-discovery/stable/get-started/index.html

## example
An example CcRuntime CR definition:

```
apiVersion: confidentialcontainers.org/v1beta1
kind: CcRuntime
metadata:
  name: ccruntime-sample
  namespace: confidential-containers-system
spec:
  # Add fields here
  runtimeName: kata
  config:
    installType: bundle
    payloadImage: quay.io/confidential-containers/runtime-payload:v0 # installer binary
    operation: <pre-install|install|uninstall|post-unihnstall>
    installVolumes:
      volumeMount:
        - name: some-config-dir
          mountPath: /host/path/to/dir
    hostRequirements:
      nodeSelector:
        feature.node.kubernetes.io/cpu-vmx: 'true' 
        ...
    
    
```

## Question: what are we missing?
