### ISSUE TITLE
latest image tags used in the release code

### ISSUE THREAD

**Issue by jtumber-ibm** [confidential-containers/operator#262]
When using a tagged version of the code the image tag specified for the manager is always latest, but the payload images are tagged to specific digests. Therefore if I try to use version `v0.7.0` it doesn't work because of the changes in the way that the runtimeclass gets created in recent updates.

https://github.com/confidential-containers/operator/blob/v0.7.0/config/manager/kustomization.yaml#L13-L16
```yaml
images:
- name: controller
  newName: quay.io/confidential-containers/operator
  newTag: latest
```

It would be benefical it the `newTag` was `v0.7.0` in this case. But I understand that that is not a simple fix as the tag gets created as part of the release process.
