### ISSUE TITLE
Add support for CC runtime installation using OS native packages

### ISSUE THREAD

**Issue by bpradipt** [confidential-containers/operator#29]
**Is your feature request related to a problem? Please describe.**
Currently, the only mechanism available to deploy the CC runtime packages are by leveraging payload image.
Payload image is a container image having all the necessary artefacts.
It'll be useful to support an alternative mechanism where the runtime packages are installed using OS native packages - rpms for Fedora/RHEL systems and debs for Ubuntu/Debian systems.

Inclavare is a CC runtime which provides rpms and debs for installation - https://github.com/inclavare-containers/inclavare-containers#installing

**Describe the solution you'd like**
Adding support for CC runtime package installation via rpm or deb

**Describe alternatives you've considered**
Alternative is using payload images and place the binaries in respective path. 

**Additional context**
In order to support installation via rpm or deb there will be some additional requirements 
1. Providing a single rpm or deb with the same name as the CC runtime `CcRuntimeName`
2. The single rpm or deb should pull in all required dependencies
3. If package installation requires a node reboot, then how to handle the same via operator.

**Comment by bpradipt** [comment]
cc @fidencio @jiazhang0

**Comment by fidencio** [comment]
@bpradipt, bear with me if I'm saying something that's not accurate, but the OS native packages, when supported, need to also map which OSes they're targetting.

From the operator side we cannot safely make assumptions about the OS, and those should come from the one providing the RPMs, so we could do a validation check before trying to install the RPMs (and finding ourselves in a broken state).

For instance, when I have a "repo" in mind, the things that automatically pop up as questions are:
* What are the supported OSes? 
  * For a supported OS, do we know how to add a repo and install a package?  More to this in a different section of this comment ...
  * For a supported OS, is there any known conflict with a base system package?
  * For a supported OS, is a reboot required?

I know, this becomes  a little bit too bureaucratic, but avoids some pitfalls that are way too easy to fall if not specified, as simply trying to install a Fedora35 built binary into a CentOS 7 host, for instance.

---

@bpradipt, the more I think about it, the more concerned I get about the complexity we'd end up adding, and let me try to explain myself here.

There's a bunch of things we can infer from the distro, and I will use CentOS as an example.

| distro  | version | supported | package manager | how to add a repo |
| - | - | - | - | - |
| CentOS | 7 |  yes, till 2024-06-30  | yum | yum-config-manager --add-repo repository_url |
| CentOS | 8 | no, EOL'd since 2021-12-31 | dnf | dnf config-manager --add-repo repository_url |
| CentOS | 8-stream | yes, till  2024-05-31  | dnf | dnf config-manager --add-repo repository_url |

Simply distinguishing those bits would add a lot of logic to the operator that is not easy to maintain, that is easy to be outdated, and that the provider of the package may know better what to do than what we can infer from the distro itself.

Mind, I'm **not** saying we should not support distro packages, that's **not** the case.  But I am saying a generic "os installer" is something yet about to be created and I don't think we should be the ones pushing for that.

Then, let's say, we somehow get things to work with CentOS and Ubuntu.  I can see issues popping out with things like "what about Flatcar?", "what aboute Fedora CoreOS?", "what about Arch?", "what about Gentoo?", and so on and so forth.

So, how do we prevent this then?

I'd love if providers could tell the us **exactly** what we need to run, something like (this is what I had in my mind as the embryo of a schema):
```
installation method: native
  - supported distros:
    - distro: centos7 // required
      - repos: [http://my_repo] // optional, in case the package is not part of the distro already // optional
      - repo-add command: yum-config-manager --add-repo // optional, in case the package is not part of the distro already // optional
      - packages: [package1, package2, ..., packageN] // required
      - id: centos // required
      - version_id: 7 // required
      - package manager: yum // required
      - installatation command: // optional, default "install"
      - uninstallation command: // optional, default to "remove"
      - known conflicts: some-package // optional, default to empty list
      - requires reboot: no //optionao, default to no
    - distro:
      - repos: ...
    ...
```

This is not a little bit bureaucratic, it's rather super bureaucratic, but that would be a way to avoid leaving all those details / logic hardcoded on the operator side that, and let us focus on actually having something deployed rather than getting lost in the weeds of being a generic package manager wrapper.

Please, let me know what are your thoughts on this, if I missed something obvious, if there's something else that should be added, etc.

**Comment by bpradipt** [comment]
@fidencio thanks a lot for thinking through this requirement and sharing your thoughts. This is super helpful. Your suggestion to provide a schema to support installation using OS native packages makes complete sense. This is also in line with similar schema definition when using payload images that is being discussed as part of #26 .

**Comment by Jakob-Naucke** [comment]
> Mind, I'm **not** saying we should not support distro packages, that's **not** the case. But I am saying a generic "os installer" is something yet about to be created and I don't think we should be the ones pushing for that.

I agree. Designing this would be (a) controversial and (b) beyond the manpower we have IMO.

**Comment by jiazhang0** [comment]
@Jakob-Naucke @fidencio @bpradipt I have discussed with @haosanzi who is the maintainer of inclavare containers project. She can make the progress on this to support your work. I believe she is quite qualified for this work.

**Comment by haosanzi** [comment]
@fidencio @bpradipt Thank you for your schema for the installation which is excellent. I can provide some installation about Inclavare Containers for this work.

Currently, Inclavare Containers provides a container runtime named rune.

We have provided packages for centos8.2 and ubtunu18.04 distro. In the future, we may provide packages for different distros.

The following is the information about how to install rune in ubuntu 18.04. 
```yaml
installation method: native
  - supported distros:
    - distro: ubuntu18.04 // required
      - repos: https://mirrors.openanolis.cn/inclavare-containers/deb-repo
      - repo-add command:
        echo 'deb [arch=amd64] https://mirrors.openanolis.cn/inclavare-containers/deb-repo bionic main' | tee /etc/apt/sources.list.d/inclavare-containers.list && wget -qO - https://mirrors.openanolis.cn/inclavare-containers/deb-repo/DEB-GPG-KEY.key  | apt-key add - 
        //rune depends on libsgx-dcap-quote-verify, we need to add sgx_repo for libsgx-dcap-quote-verify. 
        echo "deb [arch=amd64] https://download.01.org/intel-sgx/sgx_repo/ubuntu bionic main" | tee /etc/apt/sources.list.d/intel-sgx.list &&  wget -qO - https://download.01.org/intel-sgx/sgx_repo/ubuntu/intel-sgx-deb.key | apt-key add -
      - packages: rune // required
      - id: ubuntu // required
      - version_id: 18.04 // required
      - package manager: apt // required
      - installatation command: apt-get install -y rune // optional, default "install"
      - uninstallation command: apt-get remove -y rune // optional, default to "remove"
      - known conflicts:  // optional, default to empty list
      - requires reboot: no //optionao, default to no
    ...
```
