### ISSUE TITLE
Improve support for cri-o (peer-pods use case)

### ISSUE THREAD

**Issue by beraldoleal** [confidential-containers/operator#365]
**Describe the bug**
When using the operator to deploy peer-pods in a cri-o cluster, `ccruntime-per-pods` (as provided at [samples folder](https://github.com/confidential-containers/operator/blob/main/config/samples/ccruntime/peer-pods/kustomization.yaml)) will fail because preInstall scripts are not ready for cri-o environments. Also the same sample uses :

```
- patch: |-
    - op: replace
      path: /spec/config/runtimeClasses
      value:
      - name: "kata-remote"
        snapshotter: "nydus"
```

Which is assuming containerd.

**To Reproduce**

1. Install a cluster with crio.
2. kubectl apply -k https://github.com/confidential-containers/operator/config/default
3. kubectl apply -k https://github.com/confidential-containers/operator/config/samples/ccruntime/peer-pods

**Describe the results you expected**
No errors.

**Describe the results you received:**
```
$ kubectl logs pod/cc-operator-pre-install-daemon-nmmhs -n confidential-containers-system
INSTALL_COCO_CONTAINERD: false
INSTALL_OFFICIAL_CONTAINERD: false
INSTALL_VFIO_GPU_CONTAINERD: false
INSTALL_NYDUS_SNAPSHOTTER: true
ERROR: cri-o is not yet supported
```
